# Generated by Django 2.2.5 on 2020-05-22 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='restaurant name')),
                ('telefono', models.CharField(blank=True, max_length=17)),
                ('ciudad', models.CharField(default='Alicante', max_length=50, verbose_name='Ciudad')),
                ('pais', models.CharField(default='España', max_length=50, verbose_name='País')),
                ('provincia', models.CharField(default='Alicante', max_length=50, verbose_name='Provincia')),
                ('direccion', models.CharField(default='Calle España', max_length=200, verbose_name='Dirección')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='perfil')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_complete', models.BooleanField(default=False, verbose_name='complete restaurant')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='Modified at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('qr', models.ImageField(upload_to='QR')),
                ('pdf', models.FileField(upload_to='PDF')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='Modified at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.BooleanField(default=True)),
                ('lunesTurno', models.BooleanField(default=False)),
                ('lunesOpen', models.CharField(default='08:00', max_length=5)),
                ('lunesClose', models.CharField(default='13:00', max_length=5)),
                ('lunesOpen2', models.CharField(default='15:00', max_length=5)),
                ('lunesClose2', models.CharField(default='20:00', max_length=5)),
                ('martes', models.BooleanField(default=True)),
                ('martesTurno', models.BooleanField(default=False)),
                ('martesOpen', models.CharField(default='08:00', max_length=5)),
                ('martesClose', models.CharField(default='13:00', max_length=5)),
                ('martesOpen2', models.CharField(default='15:00', max_length=5)),
                ('martesClose2', models.CharField(default='20:00', max_length=5)),
                ('miercoles', models.BooleanField(default=True)),
                ('miercolesTurno', models.BooleanField(default=False)),
                ('miercolesOpen', models.CharField(default='08:00', max_length=5)),
                ('miercolesClose', models.CharField(default='13:00', max_length=5)),
                ('miercolesOpen2', models.CharField(default='15:00', max_length=5)),
                ('miercolesClose2', models.CharField(default='20:00', max_length=5)),
                ('jueves', models.BooleanField(default=True)),
                ('juevesTurno', models.BooleanField(default=False)),
                ('juevesOpen', models.CharField(default='08:00', max_length=5)),
                ('juevesClose', models.CharField(default='13:00', max_length=5)),
                ('juevesOpen2', models.CharField(default='15:00', max_length=5)),
                ('juevesClose2', models.CharField(default='20:00', max_length=5)),
                ('viernes', models.BooleanField(default=True)),
                ('viernesTurno', models.BooleanField(default=False)),
                ('viernesOpen', models.CharField(default='08:00', max_length=5)),
                ('viernesClose', models.CharField(default='13:00', max_length=5)),
                ('viernesOpen2', models.CharField(default='15:00', max_length=5)),
                ('viernesClose2', models.CharField(default='20:00', max_length=5)),
                ('sabado', models.BooleanField(default=True)),
                ('sabadoTurno', models.BooleanField(default=False)),
                ('sabadoOpen', models.CharField(default='08:00', max_length=5)),
                ('sabadoClose', models.CharField(default='13:00', max_length=5)),
                ('sabadoOpen2', models.CharField(default='15:00', max_length=5)),
                ('sabadoClose2', models.CharField(default='20:00', max_length=5)),
                ('domingo', models.BooleanField(default=True)),
                ('domingoTurno', models.BooleanField(default=False)),
                ('domingoOpen', models.CharField(default='08:00', max_length=5)),
                ('domingoClose', models.CharField(default='13:00', max_length=5)),
                ('domingoOpen2', models.CharField(default='15:00', max_length=5)),
                ('domingoClose2', models.CharField(default='20:00', max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='Modified at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
