# Generated by Django 2.2.5 on 2020-05-20 01:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='restaurant name')),
                ('telefono', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='El número de teléfono no está en el formato correcto', regex='\\+?1?\\d{9,15}$')])),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('pais', models.CharField(max_length=50, verbose_name='País')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('imagen', models.ImageField(default='default.png', upload_to='perfil')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_complete', models.BooleanField(default=False, verbose_name='complete restaurant')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='Modified at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('qr', models.ImageField(upload_to='QR')),
                ('pdf', models.FileField(upload_to='PDF')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='Modified at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.BooleanField(default=True)),
                ('lunesOpen', models.CharField(default='08:00', max_length=5)),
                ('lunesClose', models.CharField(default='20:00', max_length=5)),
                ('martes', models.BooleanField(default=True)),
                ('martesOpen', models.CharField(default='08:00', max_length=5)),
                ('martesClose', models.CharField(default='20:00', max_length=5)),
                ('miercoles', models.BooleanField(default=True)),
                ('miercolesOpen', models.CharField(default='08:00', max_length=5)),
                ('miercolesClose', models.CharField(default='20:00', max_length=5)),
                ('jueves', models.BooleanField(default=True)),
                ('juevesOpen', models.CharField(default='08:00', max_length=5)),
                ('juevesClose', models.CharField(default='20:00', max_length=5)),
                ('viernes', models.BooleanField(default=True)),
                ('viernesOpen', models.CharField(default='08:00', max_length=5)),
                ('viernesClose', models.CharField(default='20:00', max_length=5)),
                ('sabado', models.BooleanField(default=True)),
                ('sabadoOpen', models.CharField(default='08:00', max_length=5)),
                ('sabadoClose', models.CharField(default='20:00', max_length=5)),
                ('domingo', models.BooleanField(default=False)),
                ('domingoOpen', models.CharField(default='08:00', max_length=5)),
                ('domingoClose', models.CharField(default='20:00', max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='Modified at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
