# Generated by Django 2.2.5 on 2020-05-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='ciudad',
            field=models.CharField(default='Alicante', max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='direccion',
            field=models.CharField(default='Calle España', max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='pais',
            field=models.CharField(default='España', max_length=50, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='provincia',
            field=models.CharField(default='Alicante', max_length=50, verbose_name='Provincia'),
        ),
    ]
