# Generated by Django 2.2.5 on 2020-05-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200520_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='slug_name',
            field=models.CharField(default='', max_length=140),
        ),
    ]
