# Generated by Django 2.2.5 on 2020-05-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200519_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='complete restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='imagen',
            field=models.ImageField(default='default.png', upload_to='perfil'),
        ),
    ]
