# Generated by Django 2.2.5 on 2020-05-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20200520_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='provincia',
            field=models.CharField(max_length=50, verbose_name='Provincia'),
        ),
    ]
