# Generated by Django 2.2.5 on 2020-05-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20200520_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfil'),
        ),
    ]
