# Generated by Django 2.2.5 on 2020-05-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20200520_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='slug_name',
        ),
    ]
