# Generated by Django 2.2.5 on 2020-05-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_remove_restaurante_slug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='domingoClose2',
            field=models.CharField(default='20:00', max_length=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='domingoOpen2',
            field=models.CharField(default='15:00', max_length=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='domingoTurno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='juevesClose2',
            field=models.CharField(default='20:00', max_length=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='juevesOpen2',
            field=models.CharField(default='15:00', max_length=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='juevesTurno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='lunesClose2',
            field=models.CharField(default='20:00', max_length=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='lunesOpen2',
            field=models.CharField(default='15:00', max_length=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='lunesTurno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='martesClose2',
            field=models.CharField(default='20:00', max_length=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='martesOpen2',
            field=models.CharField(default='15:00', max_length=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='martesTurno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='miercolesClose2',
            field=models.CharField(default='20:00', max_length=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='miercolesOpen2',
            field=models.CharField(default='15:00', max_length=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='miercolesTurno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='sabadoClose2',
            field=models.CharField(default='20:00', max_length=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='sabadoOpen2',
            field=models.CharField(default='15:00', max_length=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='sabadoTurno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horario',
            name='viernesClose2',
            field=models.CharField(default='20:00', max_length=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='viernesOpen2',
            field=models.CharField(default='15:00', max_length=5),
        ),
        migrations.AddField(
            model_name='horario',
            name='viernesTurno',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='horario',
            name='domingo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='domingoClose',
            field=models.CharField(default='13:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='horario',
            name='juevesClose',
            field=models.CharField(default='13:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='horario',
            name='lunesClose',
            field=models.CharField(default='13:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='horario',
            name='martesClose',
            field=models.CharField(default='13:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='horario',
            name='miercolesClose',
            field=models.CharField(default='13:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='horario',
            name='sabadoClose',
            field=models.CharField(default='13:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='horario',
            name='viernesClose',
            field=models.CharField(default='13:00', max_length=5),
        ),
    ]
